processors_to_run: "0:" 
workspace_dir: /mnt/md0/common_crawl/cc_sdp/eu

processors:
  - _target_: sdp.processors.datasets.commoncrawl.PreserveByValue
    input_manifest_file: /mnt/md0/common_crawl/cc_sdp/manifest8.json
    output_manifest_file: ${workspace_dir}/manifest0.json
    input_field: audio_lang
    target_value: eu

  - _target_: sdp.processors.datasets.commoncrawl.PreserveByValue
    output_manifest_file: ${workspace_dir}/manifest1.json
    input_field: text_lang
    target_value: eu

  - _target_: sdp.processors.datasets.commoncrawl.ASR_HF
    output_manifest_file: ${workspace_dir}/manifest2.json
    pretrained_model: cahya/wav2vec2-large-xlsr-basque
    output_text_field: pred_text
    batch_size: 16

  - _target_: sdp.processors.DuplicateFields
    output_manifest_file: ${workspace_dir}/manifest3.json
    duplicate_fields: {"text":"orig_text"}

  - _target_: sdp.processors.SubRegex
    output_manifest_file: ${workspace_dir}/manifest4.json
    text_key: text
    regex_params_list:
      - {"pattern": '\[(.*?)\]', "repl": ' '}
      - {"pattern": "^[\\s]*\\*(.*?)\\*[\\s]*$", "repl": "\\1"}
      - {"pattern": '‚', "repl": ","}
      - {"pattern": "’", "repl": "'"}
      - {"pattern": "[-–—]", "repl": " "}
      - {"pattern": '―', "repl": "-"}
      - {"pattern": '—', "repl": "-"}
      - {"pattern": '⁺', "repl": "+"}
      - {"pattern": '“', "repl": '"'}
      - {"pattern": '”', "repl": '"'}
      - {"pattern": '…', "repl": '.'}
      - {"pattern": '‘', "repl": "'"}
      - {"pattern": '′', "repl": "'"}
      - {"pattern": '`', "repl": "'"}
      - {"pattern": '⁻', "repl": "-"}
      - {"pattern": '‑', "repl": "-"}
      - {"pattern": '¶', "repl": ' '}
      - {"pattern": '«', "repl": '"'}
      - {"pattern": '»', "repl": '"'}
      - {"pattern": '„', "repl": '"'}
      - {"pattern": '®', "repl": ' '}
      - {"pattern": '@', "repl": " "}
      - {"pattern": "  ", "repl": " "}

  - _target_: sdp.processors.DropHighLowWordrate
    output_manifest_file: ${workspace_dir}/manifest5.json
    high_wordrate_threshold: 100
    low_wordrate_threshold: 0.01

  - _target_: sdp.processors.DropIfRegexMatch
    output_manifest_file: ${workspace_dir}/manifest6.json
    text_key: text
    regex_patterns:
      - "^\\s*$"

  - _target_: sdp.processors.SubRegex
    output_manifest_file: ${workspace_dir}/manifest7.json
    text_key: text
    regex_params_list:
      - {"pattern": "^\\s*'+\\s(.*?)\\s*'+\\s*$", "repl": "\\1"}
      - {"pattern": "^\\s*'*\\s*", "repl": ""}
      - {"pattern": "'{2,}", "repl": "'"}
      - {"pattern": '!', "repl": '.'}
      - {"pattern": '\s(\\x[a-h][0-9]){1,}\s', "repl": ' '}
      - {"pattern": '(\\x[a-h][0-9]){1,}', "repl": ''}
      - {"pattern": '\.{3}', "repl": '.'}
      - {"pattern": '\$', "repl": ""}
      - {"pattern": "[^a-zA-ZóÓáÁéÉíÍñÑúÚüÜçÇ'.,?]", "repl": " "}
      - {"pattern": '  ', "repl": " "}

  - _target_: sdp.processors.DuplicateFields
    output_manifest_file: ${workspace_dir}/manifest8.json
    duplicate_fields: {"text":"text_pc"}

  - _target_: sdp.processors.SubMakeLowercase
    output_manifest_file: ${workspace_dir}/manifest9.json
    text_key: text

  - _target_: sdp.processors.SubRegex
    output_manifest_file: ${workspace_dir}/manifest10.json
    text_key: text
    regex_params_list:
      - {"pattern": "[\\?\\.]", "repl": " "}
      - {"pattern": ",", "repl": " "}
      - {"pattern": "  ", "repl": " "}

  - _target_: sdp.processors.DropIfRegexMatch
    output_manifest_file: ${workspace_dir}/manifest11.json
    text_key: text
    regex_patterns:
      - "^\\s*$"

  - _target_: sdp.processors.DropHighWER
    output_manifest_file: ${workspace_dir}/manifest12.json
    text_key: text
    pred_text_key: pred_text
    wer_threshold: 75

  - _target_: sdp.processors.DropHighCER
    output_manifest_file: ${workspace_dir}/manifest13.json
    text_key: text
    pred_text_key: pred_text
    cer_threshold: 30
    