processors_to_run: "14:"
workspace_dir: /mnt/md0/common_crawl/cc_sdp/de_en

processors:
  - _target_: sdp.processors.datasets.cc.cc.PreserveByValue
    input_manifest_file: /mnt/md0/common_crawl/cc_sdp/manifest8ps.json
    output_manifest_file: ${workspace_dir}/manifest0.json
    input_field: audio_lang
    target_value: de

  - _target_: sdp.processors.datasets.cc.cc.PreserveByValue
    output_manifest_file: ${workspace_dir}/manifest1.json
    input_field: text_lang
    target_value: en
  
  - _target_: sdp.processors.ASRInference
    output_manifest_file: ${workspace_dir}/manifest2.json
    pretrained_model: nvidia/stt_de_fastconformer_hybrid_large_pc
    batch_size: 64

  - _target_: sdp.processors.DuplicateFields
    output_manifest_file: ${workspace_dir}/manifest3.json
    duplicate_fields: {"text":"orig_text"}

  - _target_: sdp.processors.RenameFields
    output_manifest_file: ${workspace_dir}/manifest4.json
    rename_fields: {"pred_text": "asr_text"}

  - _target_: sdp.processors.DropIfRegexMatch
    output_manifest_file: ${workspace_dir}/manifest5.json
    text_key: asr_text
    regex_patterns:
      - "^\\s*$"

  - _target_: sdp.processors.datasets.cc.cc.NmtSubprocess
    output_manifest_file: ${workspace_dir}/manifest6.json
    arg_separator: "="
    srctext_file: ${workspace_dir}/srctext.txt # --srctext=${workspace_dir}/srctext.txt
    tgtout_file: ${workspace_dir}/tgtout.txt # --tgtout=${workspace_dir}/tgtout.txt
    input_field: "asr_text"
    output_field: "pred_text"
    cmd: "python /home/nkarpov/workspace/NeMo/examples/nlp/machine_translation/nmt_transformer_infer.py \
        --model=${workspace_dir}/nmt_de_en_transformer12x2.nemo --target_lang=en --source_lang=de"

  - _target_: sdp.processors.SubRegex
    output_manifest_file: ${workspace_dir}/manifest7.json
    regex_params_list:
      - {"pattern": '\[(.*?)\]', "repl": ' '}
      - {"pattern": "^[\\s]*\\*(.*?)\\*[\\s]*$", "repl": "\\1"}
      - {"pattern": 'î', "repl": "i"}
      - {"pattern": 'ì', "repl": "i"}
      - {"pattern": 'í', "repl": "i"}
      - {"pattern": '‚', "repl": ","}
      - {"pattern": "’", "repl": "'"}
      - {"pattern": "[-–—]", "repl": " "}
      - {"pattern": '―', "repl": "-"}
      - {"pattern": '—', "repl": "-"}
      - {"pattern": '⁺', "repl": "+"}
      - {"pattern": '“', "repl": '"'}
      - {"pattern": '”', "repl": '"'}
      - {"pattern": '…', "repl": '.'}
      - {"pattern": '‘', "repl": "'"}
      - {"pattern": '′', "repl": "'"}
      - {"pattern": '`', "repl": "'"}
      - {"pattern": '⁻', "repl": "-"}
      - {"pattern": '‑', "repl": "-"}
      - {"pattern": '¶', "repl": ' '}
      - {"pattern": '«', "repl": '"'}
      - {"pattern": '»', "repl": '"'}
      - {"pattern": '„', "repl": '"'}
      - {"pattern": '®', "repl": ' '}
      - {"pattern": "  ", "repl": " "}

  - _target_: sdp.processors.DropHighLowWordrate
    output_manifest_file: ${workspace_dir}/manifest8.json
    high_wordrate_threshold: 100
    low_wordrate_threshold: 0.01

  - _target_: sdp.processors.datasets.cc.cc.Subprocess
    output_manifest_file: ${workspace_dir}/manifest9.json
    input_manifest_arg: "--manifest"
    output_manifest_arg: "--output_filename"
    arg_separator: "="
    cmd: "python /home/nkarpov/workspace/NeMo-text-processing/nemo_text_processing/text_normalization/normalize_with_audio.py \
        --language=en --n_jobs=-1 --batch_size=600 --manifest_text_field=text --cache_dir=${workspace_dir}/cache --overwrite_cache \
        --whitelist=/home/nkarpov/workspace/NeMo-text-processing/nemo_text_processing/text_normalization/en/data/whitelist/asr_with_pc.tsv"

  - _target_: sdp.processors.RenameFields
    output_manifest_file: ${workspace_dir}/manifest10.json
    rename_fields: {"normalized":"text"}

  - _target_: sdp.processors.SubRegex
    output_manifest_file: ${workspace_dir}/manifest11.json
    text_key: text
    regex_params_list:
      - {"pattern": "^\\s*'+\\s(.*?)\\s*'+\\s*$", "repl": "\\1"}
      - {"pattern": "^\\s*'*\\s*", "repl": ""}
      - {"pattern": "'{2,}", "repl": "'"}
      - {"pattern": '\\.{3}', "repl": '.'}
      - {"pattern": '\$', "repl": ""}
      - {"pattern": "[^A-Za-zäöüÄÖÜß'.,?]", "repl": " "}
      - {"pattern": '  ', "repl": " "}
    test_cases:
      - {input: {text: "' jupiter and venus both shining in the golden rosy sky"}, output: {text: "jupiter and venus both shining in the golden rosy sky"}}
      - {input: {text: "' may all the gold i have ever dreamed of be yours '"}, output: {text: "may all the gold i have ever dreamed of be yours"}}
      - {input: {text: "''cause it''s an adult novel versus ya"}, output: {text: "cause it's an adult novel versus ya"}}


  - _target_: sdp.processors.DropIfRegexMatch
    output_manifest_file: ${workspace_dir}/manifest12.json
    text_key: text
    regex_patterns:
      - "^\\s*$"

  - _target_: sdp.processors.datasets.cc.cc.BLEUScore
    output_manifest_file: ${workspace_dir}/manifest13.json
    ref_field: text
    hyp_field: pred_text
    output_field: bleu

  - _target_: sdp.processors.datasets.cc.cc.UseSonar
    output_manifest_file: ${workspace_dir}/manifest14.json
    input_text_field: text
    input_audio_field: audio_filepath
    output_field: sonar_dist
    device: cuda
    speech_encoder_model: sonar_speech_encoder_deu
    text_encoder_model: text_sonar_basic_encoder
    text_encoder_lang: eng_Latn
    batch_size: 64

  - _target_: sdp.processors.datasets.cc.cc.PreserveByValue
    output_manifest_file: ${workspace_dir}/manifest15s.json
    input_field: sonar_dist
    target_value: 0.1
    operator: le

  # - _target_: sdp.processors.datasets.cc.cc.PreserveByValue
  #   output_manifest_file: ${workspace_dir}/manifest15.json
  #   input_field: bleu
  #   target_value: 10
  #   operator: ge