processors_to_run: "3:"
workspace_dir: /mnt/ssd8/cc_sdp/fr

processors:
  - _target_: sdp.processors.datasets.commoncrawl.PreserveByValue
    input_manifest_file: /mnt/ssd8/cc_sdp/manifest7.json
    output_manifest_file: ${workspace_dir}/manifest0.json
    input_field: audio_lang
    preserve_value: fr

  - _target_: sdp.processors.datasets.commoncrawl.PreserveByValue
    output_manifest_file: ${workspace_dir}/manifest1.json
    input_field: text_lang
    preserve_value: fr
    
  - _target_: sdp.processors.ASRInference
    input_manifest_file: ${workspace_dir}/manifest1.json
    output_manifest_file: ${workspace_dir}/manifest2.json
    pretrained_model: nvidia/stt_fr_conformer_transducer_large # nvidia/stt_fr_fastconformer_hybrid_large_pc
    batch_size: 64

  - _target_: sdp.processors.DuplicateFields
    duplicate_fields: {"text":"orig_text"}

  - _target_: sdp.processors.DropIfRegexMatch
    input_manifest_file: ${workspace_dir}/manifest2.json
    output_manifest_file: ${workspace_dir}/manifest3.json
    regex_patterns:
    # â à    ê è È é É ë  î ì ï  ô    û ù ü  ÿ   ç œ  æ 
      # - '://'
      - '\\x'
      - '×'
      - '½'
      - 'š'
      - '⁶'
      - 'ö'
      - 'ß'
      - 'ä'
      - 'ü'
      - '\u202a'
      - 'č'
      - 'ć'
      - 'á'
      - 'ã'
      - 'ï'
      - '²'
      - '\u2060'
      - '°'
      - 'ñ'
      - 'ŵ'
      - 'ù'
      - 'ò'
      - 'ó'
      - 'ő'
      - 'ă'
      - 'ú'
      - 'µ'
      - '¿'
      - 'ë'
      - "%"
  

  - _target_: sdp.processors.SubRegex
    # input_manifest_file: ${workspace_dir}/manifest3.json
    output_manifest_file: ${workspace_dir}/manifest4.json
    max_workers: 20
    regex_params_list:
      - {"pattern": '¡', "repl": "i"}
      - {"pattern": '‚', "repl": ","}
      - {"pattern": "’", "repl": "'"}
      - {"pattern": "[-–—]", "repl": " "}
      - {"pattern": '―', "repl": "-"}
      - {"pattern": '—', "repl": "-"}
      - {"pattern": '⁺', "repl": "+"}
      - {"pattern": '“', "repl": '"'}
      - {"pattern": '”', "repl": '"'}
      - {"pattern": '…', "repl": '.'}
      - {"pattern": '‘', "repl": "'"}
      - {"pattern": '′', "repl": "'"}
      - {"pattern": '`', "repl": "'"}
      - {"pattern": '⁻', "repl": "-"}
      - {"pattern": '‑', "repl": "-"}
      - {"pattern": '¶', "repl": ' '}
      - {"pattern": '«', "repl": '"'}
      - {"pattern": '»', "repl": '"'}
      - {"pattern": '„', "repl": '"'}
      - {"pattern": '®', "repl": ' '}
      - {"pattern": '@', "repl": " "}
      - {"pattern": "  ", "repl": " "}

  - _target_: sdp.processors.DropHighLowWordrate
    # input_manifest_file: ${workspace_dir}/manifest4.json
    output_manifest_file: ${workspace_dir}/manifest5.json
    high_wordrate_threshold: 1000
    low_wordrate_threshold: 0.001


  - _target_: sdp.processors.SubRegex
    # input_manifest_file: ${workspace_dir}/manifest5.json
    output_manifest_file: ${workspace_dir}/manifest6.json
    regex_params_list:
      # - {"pattern": "'", "repl": " "}
      # - {"pattern": '\-', "repl": " "}
      # - {"pattern": '[\[\]\":\(\);\\\+\*]', "repl": ' '}
      - {"pattern": '=', "repl": " "}
      - {"pattern": '$', "repl": " "}
      - {"pattern": '#', "repl": " "}
      - {"pattern": '/', "repl": " "}
      - {"pattern": '>', "repl": " "}
      - {"pattern": '<', "repl": " "}
      - {"pattern": '&', "repl": " "}
      - {"pattern": '@', "repl": " "}
      - {"pattern": '\\.{3}', "repl": '.'}
      - {"pattern": '  ', "repl": " "}


  - _target_: sdp.processors.DropHighLowWordrate
    # input_manifest_file: ${workspace_dir}/manifest6.json
    output_manifest_file: ${workspace_dir}/manifest7.json
    high_wordrate_threshold: 100
    low_wordrate_threshold: 0.01

  - _target_: sdp.processors.DuplicateFields
    # input_manifest_file: ${workspace_dir}/manifest7.json
    output_manifest_file: ${workspace_dir}/manifest8.json
    duplicate_fields: {"text":"text_pc"}

  - _target_: sdp.processors.SubMakeLowercase
    output_manifest_file: ${workspace_dir}/manifest9.json
    text_key: text

  - _target_: sdp.processors.SubRegex
    output_manifest_file: ${workspace_dir}/manifest10.json
    text_key: text
    regex_params_list:
      - {"pattern": "[\\?\\.\\!]", "repl": " "}
      - {"pattern": ",", "repl": " "}
      - {"pattern": "  ", "repl": " "}

  - _target_: sdp.processors.DuplicateFields
    output_manifest_file: ${workspace_dir}/manifest11.json
    duplicate_fields: {"pred_text":"pred_text_pc"}

  - _target_: sdp.processors.SubMakeLowercase
    output_manifest_file: ${workspace_dir}/manifest12.json
    text_key: pred_text

  - _target_: sdp.processors.SubRegex
    output_manifest_file: ${workspace_dir}/manifest13.json
    text_key: pred_text
    regex_params_list:
      - {"pattern": "[\\?\\.\\!]", "repl": " "}
      - {"pattern": ",", "repl": " "}
      - {"pattern": "  ", "repl": " "}

  - _target_: sdp.processors.DropHighWER
    input_manifest_file: ${workspace_dir}/manifest13.json
    output_manifest_file: ${workspace_dir}/manifest14.json
    text_key: text
    pred_text_key: pred_text
    wer_threshold: 75

  - _target_: sdp.processors.DropHighCER
    input_manifest_file: ${workspace_dir}/manifest14.json
    output_manifest_file: ${workspace_dir}/manifest15.json
    text_key: text
    pred_text_key: pred_text
    cer_threshold: 30
    